coroutine.wrap(function()
local discordia = require('discordia')
local client = discordia.Client()
discordia.extensions()
local json = require("json")
local dbFile = require("./modules/db")
local fs = require("fs")
local events = require("./modules/events")
local misc = require("./modules/misc")

local config = json.decode(misc.readAll("config.json"))

client:on("messageCreate", events.messageCreate)
client:on("guildCreate", events.guildCreate)
client:on("guildUpdate", events.guildUpdate)
client:on("guildDelete", events.guildDelete)
client:on("channelDelete", events.channelDelete)

client:once("ready", function()
    discordia.storage.uptime = discordia.Stopwatch()
    client:setGame({ type = 3, name = "for h[help" })
    misc.cmdHook(client, nil, "info", "start", nil, nil, nil)
end)

client:run("Bot " .. config["token"])
end)()